### ISSUE TITLE
Oct 5 - Oct 9 - End-to-End App Development Using Visual Studio Code 

### ISSUE THREAD

**Issue by mebaumb** [microsoft/ReactorPlanning#109]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Coding, Languages, and Frameworks |
| Monthly Topic (if applicable) | Open Source |
| Weekly Topic (if applicable) |  VS Code |
| Workshop Topic | Build, integrate and deploy a Node.js app in VS Code |
| Workshop Duration | 60 mins | 
| Title | End-to-End App Development Using Visual Studio Code |
| Description | <p>Get ready to get comfortable developing apps in Visual Studio Code. This workshop begins with a tour of Visual Studio Code to ensure you have the basics before creating a simple web app with Node.js and Express. From there, you'll deploy your app to Azure App Service and then integrate the app with the built-in source control feature and deploy to GitHub.</p><p>Prerequisites: No prior knowledge of Node.js or Express is needed. To follow along, install Visual Studio Code (https://code.visualstudio.com/Download), Node.js (https://nodejs.org/en/download/), Git (https://git-scm.com/downloads), and create accounts for Azure (https://azure.microsoft.com/free/) and GitHub (https://github.com/join).</p>|
| Links to Content | [Create and publish a web application with Azure App Service and Visual Studio Code](https://docs.microsoft.com/learn/modules/create-publish-webapp-app-service-vs-code//?WT.mc_id=reactor-github-reactor), [Use Git version-control tools in Visual Studio Code](https://docs.microsoft.com/learn/modules/use-git-from-vs-code//?WT.mc_id=reactor-github-reactor) |

# Workshop(s) details
| Date |  Local Start Time |  Location |  Speaker | SharePoint ID | Platform |
|------|-------------------|-----------|----------|---------------|----------|
| Oct 6 | 6:30 pm (Bangalore) | Bangalore | TBD | 11619 | N/A |
| Oct 6 | 4:00 PM PST | US/Canada/Sydney | Will Goode (Chris Bautista Moderator) | 7965 | N/A |
| Oct 7 | 7:30 pm | Sao Paulo | TBD | 7963 | N/A |
| Oct 18 | 7:30 pm | Shanghai | TBD | 7934 | N/A |
| Oct 7 | 5:00 PM (London) | London, Stockholm, Abu Dhabi, Tel Aviv (No stream TA) | TBD | 7964 | N/A |

# Event Checklist

## 10 Weeks Prior
- [x] Reactor Content Team (RCT) opens a new issue for an upcoming local workshop filling in the Event Information and Workshop details tables. RCT member who owns content (content owner) this week will be the assignee.
- [x] RCT and content owner discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and _local-digital-event_ tag to the issue and adds event to the __Local Digital Events__ project. Issue will appear in the __Upcoming Streams__ column
- [x] RCT adds a _ready-for-marketing-edit_ label so the RCT can review title and description

## 8 Weeks Prior
- [x] RCT does a review of title and description and removes the _ready-for-marketing-edit_ label 
- [x] RCT moves the issue to the __Ready for SharePoint__ column
- [x] RCT informs the Reactor Marketing Team of the new event information
- [x] RCT confirms the speaker
- [x] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT moves the issue to the __Content Preparation In Progress__ column

## 5 weeks Prior
- [x] Content owner opens a PR with the new content for the workshop on the [customer-facing Reactor repository](https://github.com/microsoft/Reactors/tree/main/online-event-resources) and adds the _content-development_ and _local-digital-event_ tag to the PR. 
- [x] RCT reviews, approves, and merges the changes
- [x] RCT shares content with the vendor/instructor
- [x] RCT provides vendor/instructor with assets (e.g. slides, overlays) and the survey data for the event
- [x] RCT ensures that instructors have received an invite to the workshops and that PM team works with instructors to get setup in the platform (e.g. Teams, Teams Live Event)

## 1 Week Prior
- [x] Connect vendor/instructor with the PM(s) for the locations where this event has been marketed
- [x] Check-in with vendor/instructor that they are prepared for the workshop
- [x] RCT moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Instructor (and optional moderator) run the stream
- [ ] _(Optional)_RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by mebaumb** [comment]
@KimberlyBolton1 I don't know if you saw this! :) 

Added the events in Dynamics (still need to update with final title/abstract)

**Comment by KimberlyBolton1** [comment]
@meaghanlewis, are you the reviewer? here's the edit. I removed the references to Express and Node.js as it made the title too long and it seemed VS code was the bigger focus.

**End-to-End App Development Using Visual Studio Code**
Get ready to get comfortable developing apps in Visual Studio Code. This workshop begins with a tour of Visual Studio Code to ensure you have the basics before creating a simple web app with Node.js and Express.. From there, you'll deploy your app to Azure App Service and then integrate the app with the built-in source control feature and deploy to GitHub. 
Prerequisites: No prior knowledge of Node.js or Express is needed. To follow along, install Visual Studio Code (https://code.visualstudio.com/Download), Node.js (https://nodejs.org/en/download/), Git (https://git-scm.com/downloads), and accounts for Azure (https://azure.microsoft.com/free/) and GitHub (https://github.com/join).

**Comment by meaghanlewis** [comment]
Thank you @KimberlyBolton1 for the edit and adding those links!

One thing is that Express.js should just be referred to as Express. That was my bad.

**Comment by meaghanlewis** [comment]
I edited your edit!

**Comment by meaghanlewis** [comment]
Here's an overview of what this workshop will cover and suggested agenda to follow with links and resources.

## Content to teach
This workshop will take Reactor community members through two modules on Microsoft Learn. 
- [Create and publish a web application with Azure App Service and Visual Studio Code](https://docs.microsoft.com/learn/modules/create-publish-webapp-app-service-vs-code//?WT.mc_id=reactor-github-reactor)
- [Use Git version-control tools in Visual Studio Code](https://docs.microsoft.com/learn/modules/use-git-from-vs-code//?WT.mc_id=reactor-github-reactor)

**These links should be shared with attendees during the workshop:**
- https://aka.ms/PublishAppsAzureAppSvcs-8
- https://aka.ms/GitToolsinVSC-8

Encourage attendees to go through module with you and complete it so that they get an acheivement badge in their profile.

## Workshop Steps
This is how I would walk through and teach these two modules. You'll notice I just linked directly to the specific sections for reference.

1.  [Introduction](https://docs.microsoft.com/en-us/learn/modules/create-publish-webapp-app-service-vs-code/1-introduction)
2. [Overview](https://docs.microsoft.com/en-us/learn/modules/create-publish-webapp-app-service-vs-code/2-create-web-application-vs-code?pivots=nodeexpress)
    - What is VS Code
      - https://code.visualstudio.com
    - What is Node.js
      - Show how to install: https://nodejs.org/en/download/
    - What is Express
      - https://expressjs.com/

3. [Create a web app with Visual Studio Code (using Node.js and Express.js)](https://docs.microsoft.com/en-us/learn/modules/create-publish-webapp-app-service-vs-code/3-exercise-create-web-application-vs-code?pivots=nodeexpress)

4. [Publish a web app with Azure App Service](https://docs.microsoft.com/en-us/learn/modules/create-publish-webapp-app-service-vs-code/4-publish-app-azure-app-service-vs-code)
    - What is Azure App Service: https://azure.microsoft.com/services/app-service/
      - Remind attendees that they need an Azure account for this
    - What is an App Service Plan: https://azure.microsoft.com/pricing/details/app-service/windows/
    - What is the VS Code App Service extension: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azureappservice
  5. [Deploy a website](https://docs.microsoft.com/en-us/learn/modules/create-publish-webapp-app-service-vs-code/5-exercise-publish-app-azure-app-service-vs-code?pivots=nodeexpress)
  6. [Push updates to Azure App Service](https://docs.microsoft.com/en-us/learn/modules/create-publish-webapp-app-service-vs-code/6-update-app-vs-code-publish-updates)

7. Integrate with Git + GitHub
    - Initialize project as git repo. Push to GitHub. Can share repo link with attendees or encourage them to create their own.
    - [How to clone and create a branch](https://docs.microsoft.com/en-us/learn/modules/use-git-from-vs-code/2-exercise-clone-branch)
    - [Update app and publish new version to App Service](https://docs.microsoft.com/en-us/learn/modules/create-publish-webapp-app-service-vs-code/7-exercise-update-app-vs-code-publish-updates?pivots=nodeexpress)
    - [Stage, commit, push changes to remote repository](https://docs.microsoft.com/en-us/learn/modules/use-git-from-vs-code/3-exercise-stage-commit)
8. Closing
    - Q&A
    - Survey: https://aka.ms/Reactor/Survey
      - Note: The event code is listed in this issue description and/or your Reactor contact can share that with the community members
    - Share Resources 
    - Check if the Reactor contact has other information to share   

## Other resources about building and deploying apps
Please share out these additional resources at the end
  - [Build a Node.js app for Cosmos DB](https://aka.ms/BuildNodeComsosDB-8)
  - [Node.js tutorial in Visual Studio Code](https://code.visualstudio.com/docs/nodejs/nodejs-tutorial)
  - [App Service Documentation](https://docs.microsoft.com/azure/app-service/)
  - [Azure App Service plan overview](https://docs.microsoft.com/azure/app-service/overview-hosting-plans)
  - [Set up staging environments in Azure App Service](https://docs.microsoft.com/azure/app-service/deploy-staging-slots)

**Comment by KimberlyBolton1** [comment]
@mebaumb Abstract final and moved to Ready for SharePoint.

**Comment by mebaumb** [comment]
Updated title/abstract in all locations.

Published the workshop for US/Canada as we have speaker confirmed from CD

**Comment by mebaumb** [comment]
Abstract sent to Caio for translation.

**Comment by mebaumb** [comment]
Bangalore, Sao Paulo, Shanghai and London/Stockholm/Abu Dhabi/Tel Aviv have been published without speaker info (9/2)

**Comment by mebaumb** [comment]
All workshops have been delivered except for Shanghai which was moved to 10/18
